<?php
/**
 * Represents a page in the admin section of a Haddock project.
 * 
 * Eventually all pages in the admin section should
 * be generated by subclasses of this.
 *
 * @copyrigh Clear Line Web Design, 2007-12-12
 */

abstract class
	Admin_HTMLPage
extends
	PublicHTML_HTMLPage
{
	protected function
		render_head_link_stylesheet()
	{
		HTMLTags_LinkRenderer::render_style_sheet_link('/admin/styles/styles.css');
	}
}
?>