<?php
/**
 * The search overrides of the PublicHTML_PageManager
 * are set in this file.
 *
 * By default, nothing is set.
 * It is assumed that the overrides will be set in files
 * that override this one.
 *
 * It is also assumed that the files that override this
 * one will be generated by the inc-file-finder script
 * in haddock-project-organisation.
 *
 * @copyright Clear Line Web Design, 2007-07-30
 */

//echo '__FILE__: ' . "\n";
//echo __FILE__ . "\n";
#exit;
?>
